name: Continuous integration
on: [push]
jobs:
  all:
    name: Lint, build, and test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install frontend requirements
      run: npm ci
      working-directory: ./Frontend
    - name: Lint frontend
      run: npm run lint
      working-directory: ./Frontend
    - name: Build frontend
      run: npm run build
      working-directory: ./Frontend
    - name: Test frontend
      run: npm run test
      working-directory: ./Frontend
    - name: Install backend requirements
      run: npm ci
      working-directory: ./Backend
    - name: Lint backend
      run: npm run lint
      working-directory: ./Backend
    - name: Test backend
      run: npm run test
      working-directory: ./Backend
