name: Continuous integration
on: [push]
jobs:
  frontend:
    name: Lint, build, and test frontend
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install
      run: npm ci
      working-directory: ./Backend
    - name: Lint
      run: npm run lint
      working-directory: ./Backend
    - name: Test
      run: npm run test
      working-directory: ./Backend
  backend:
    name: Lint, build, and test backend
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install
      run: npm ci
      working-directory: ./Frontend
    - name: Lint
      run: npm run lint
      working-directory: ./Frontend
    - name: Build
      run: npm run build
      working-directory: ./Frontend
    - name: Test
      run: npm run test
      working-directory: ./Frontend
